
- name: task day2
  package:
    name: "{{x}}"
    state: present
  notify: hand

- name: template file
  template:
    src: ./index.html.j2 
    dest: /var/www/html/index.html
  notify: hand2 
  
  
